language: node_js

cache:
  directories:
    - ~/.npm

git:
  depth: 5

node_js:
  - '6'
  - '7'

addons:
  browserstack:
    username: "mattmcfarland2"
    access_key: "8XtpNwsCV785G5gStzgP"

before_install:
  - npm config set spin false --global

install:
  - npm install

script:
  - npm test && npm run lint && npm run test:remote

